import type { Metadata } from "next";
import "./globals.css";
import "highlight.js/styles/stackoverflow-dark.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <div className="pt-8 pb-10 lg:pt-12 lg:pb-14 mx-auto max-w-7xl px-2">
                    <div className="max-w-2xl mx-auto">{children}</div>
                </div>
            </body>
        </html>
    );
}
